---
title: "Origin of Yamanaka expression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(powerjoin)
library(data.table)
library(synExtra)
library(ggbeeswarm)

# library(rtracklayer)
# library(graphics)
# library(ggcoverage)
# library(ggpattern)

synapser::synLogin()

syn <- synDownloader("~/data", .cache = TRUE)
```

## Metadata

```{r}
inputs <- c(
  sample_meta = "syn53061904",
  size_factors = "syn53061911",
  yamanaka_ratios_star = "syn53067575",
  yamanaka_feature_counts_star = "syn53067574",
  salmon_tpm_yamanaka = "syn53088792"
)

input_files <- map(
  inputs, syn
)
sample_meta <- read_csv(input_files[["sample_meta"]])
size_factors <- read_csv(input_files[["size_factors"]])
yamanaka_ratios_star <- read_csv(input_files[["yamanaka_ratios_star"]])
yamanaka_feature_counts_star <- read_csv(input_files[["yamanaka_feature_counts_star"]])
salmon_tpm_yamanaka <- read_csv(input_files[["salmon_tpm_yamanaka"]])
```

```{r}
ensembl_gtf <- rtracklayer::import.gff(
    con = here("index", "Homo_sapiens.GRCh38.110.gtf.gz"), format = "gtf"
)

yamanaka_factors <- c("KLF4", "MYC", "POU5F1", "SOX2")

yamanaka_gtf <- ensembl_gtf[
  ensembl_gtf$gene_name %in% yamanaka_factors &
    replace_na(str_detect(ensembl_gtf$tag, "MANE_Select"), FALSE)
]

yamanaka_utrs <- yamanaka_gtf[
  str_detect(yamanaka_gtf$type, "utr")
]

yamanaka_cds <- yamanaka_gtf[
  yamanaka_gtf$type == "CDS"
] %>%
  S4Vectors::split(.$gene_id)

yamanaka_lengths <- yamanaka_utrs %>%
  as_tibble() %>%
  bind_rows(
    yamanaka_cds %>%
      as_tibble()
  ) %>%
  transmute(
    type, gene_id, gene_name,
    length = width
  ) %>%
  group_by(type, gene_id, gene_name) %>%
  summarize(length = sum(length), .groups = "drop")

```


```{r}
yamanaka_feature_counts_star_rpk <- yamanaka_feature_counts_star %>%
  group_by(feature_name, sample_accession, gene_id, gene_name) %>%
  summarize(
    across(
      c(count, normalized_count),
      sum
    ),
    .groups = "drop"
  ) %>%
  power_inner_join(
    yamanaka_lengths %>%
      mutate(feature_name = if_else(type == "CDS", "cds", "utrs")) %>%
      group_by(feature_name, gene_id, gene_name) %>%
      summarize(
        across(
          c(length),
          sum
        ),
        .groups = "drop"
      ),
    by = c("feature_name", "gene_id", "gene_name"),
    check = check_specs(
      unmatched_keys_left = "warn",
      unmatched_keys_right = "warn",
      duplicate_keys_right = "warn"
    )
  ) %>%
  mutate(
    rpk = 1000 * normalized_count / length
  )
```

```{r}
yamanaka_ratios_rpk <- yamanaka_feature_counts_star_rpk %>%
  select(-length) %>%
  pivot_longer(
    c(count, normalized_count, rpk),
    names_to = "count_type",
    values_to = "count"
  ) %>%
  pivot_wider(
    names_from = feature_name,
    values_from = count,
    names_prefix = "count_"
  ) %>%
  mutate(
    ratio = count_cds / count_utrs
  )
```


```{r}
p <- yamanaka_ratios_rpk %>%
  filter(count_type == "rpk") %>%
  ggplot(aes(x = gene_name, y = ratio)) +
    geom_hline(yintercept = 1, linetype = "dashed") +
    geom_quasirandom() +
    scale_y_log10(

    ) +
    labs(
      y = "CDS / UTR ratio", x = NULL
    )

ggsave(
  here("plots", "yamanaka_ratios_star_rpk.pdf"),
  p, width = 4, height = 3
)
```


```{r}
salmon_yamanaka_ratios <- salmon_tpm_yamanaka %>%
  filter(str_detect(transcript_id, "with_utr|no_utr")) %>%
  extract(
    transcript_id,
    into = c("gene_name", "feature_name"),
    regex = "([A-Z0-9]+)-[0-9]+_(with_utr|no_utr)"
  ) %>%
  select(-count) %>%
  pivot_wider(
    names_from = feature_name,
    values_from = tpm
  ) %>%
  mutate(
    ratio = no_utr / with_utr,
    transcript_ratio = (with_utr + no_utr) / with_utr
  )

# utr = with_utr
# cds = with_utr + without_utr
```

```{r}
yamanaka_both_ratios <- yamanaka_ratios_rpk %>%
  filter(count_type == "rpk") %>%
  rename(ratio_rpk = ratio) %>%
  power_inner_join(
    salmon_yamanaka_ratios %>%
      rename(ratio_tpm = ratio, transcript_ratio_tpm = transcript_ratio),
    by = c("gene_name", "sample_accession"),
    check = check_specs(
      unmatched_keys_left = "warn",
      unmatched_keys_right = "warn"
    )
  )

write_csv(
  yamanaka_both_ratios,
  here("quants", "yamanaka_ratios.csv.gz")
)
```


```{r}
syn_quants_dir <- synMkdir("syn53061839", "quants")

synStoreMany(
  c(
    here("quants", "yamanaka_ratios.csv.gz")
  ),
  parentId = syn_quants_dir,
  forceVersion = FALSE
)
```

```{r}

p <- yamanaka_both_ratios %>%
  mutate(
    total_count = count_cds + count_utrs,
    counts_low = total_count < 50
  ) %>%
  ggplot(
    aes(x = ratio_rpk, y = ratio_tpm, color = counts_low)
  ) +
    geom_point() +
    scale_color_manual(
      values = c(`TRUE` = "gray", `FALSE` = "black")
    ) +
    scale_x_log10() +
    scale_y_log10() +
    facet_wrap(~gene_name)

p <- yamanaka_both_ratios %>%
  mutate(
    total_count = count_cds + count_utrs,
    counts_low = total_count < 50
  ) %>%
  ggplot(
    aes(x = ratio_rpk, y = transcript_ratio_tpm, color = counts_low)
  ) +
    geom_point() +
    scale_color_manual(
      values = c(`TRUE` = "gray", `FALSE` = "black")
    ) +
    scale_x_log10() +
    scale_y_log10() +
    coord_equal() +
    facet_wrap(~gene_name) +
    labs(
      x = "CDS / UTR ratio STAR",
      y = " CDS / UTR ratio Salmon"
    )

ggsave(
  here("plots", "yamanaka_ratios_star_vs_salmon.pdf"),
  p, width = 7, height = 4
)
```


```{r}
sample_meta_edited <- sample_meta %>%
  mutate(
    treatment = case_when(
      treatment == "Naïve" ~ "t2iLGoY",
      cell_type == "primed hESC" ~ "Primed",
      cell_type == "naive hESC" ~ "Naïve",
      source_name == "5iLAF SSEA4- subpopulation UCLA1 hESCs" ~ "Control ESC",
      TRUE ~ treatment
    )
  )


plot_samples <- sample_meta_edited %>%
  filter(
    treatment == "Fibroblast",
    time_point %in% c("P8", "P20 + 3")
  ) %>%
  mutate(
    time_point_plot = "D0",
    sample_group = "Fibroblast D0"
  ) %>%
  bind_rows(
    # Naive Sendai treated
    sample_meta_edited %>%
      filter(
        treatment %in% c("t2iLGoY"),
        time_point == "P15"
      ) %>%
      mutate(
        time_point_plot = "P15",
        sample_group = "Naïve P15"
      )
  ) %>%
  bind_rows(
    # Primed Sendai treated
    sample_meta_edited %>%
      filter(
        treatment %in% c("Primed"),
        tissue == "iPSCs" | is.na(tissue),
        study_name %in% c("Buckberry Nature 2023", "Liu Nature 2020", "Liu Nat Met 2017"),
        time_point %in% c("P17", "P18")
      ) %>%
      mutate(
        time_point_plot = "P17/18",
        sample_group = "Primed P17/18"
      )
  ) %>%
  bind_rows(
    # ESC
    sample_meta_edited %>%
      filter(
        treatment %in% c("Control ESC") |
          (replace_na(tissue == "ESCs", FALSE) & treatment == "Primed") |
          study_name == "Ji CSC 2016"
      ) %>%
      mutate(
        time_point_plot = "ESC",
        sample_group = "ESC"
      )
  ) %>%
  bind_rows(
    # TNT
    sample_meta_edited %>%
      filter(
        treatment %in% c("TNT")
      ) %>%
      mutate(
        time_point_plot = "P17/18",
        sample_group = "TNT P17/18"
      )
  ) %>%
  bind_rows(
    # NtP
    sample_meta_edited %>%
      filter(
        treatment %in% c("NtP")
      ) %>%
      mutate(
        time_point_plot = "P9/15",
        sample_group = "NtP P9/15"
      )
  ) %>%
  mutate(
    sample_group = factor(
      sample_group,
      levels = c("Fibroblast D0", "Primed P17/18", "TNT P17/18", "NtP P9/15", "Naïve P15", "ESC")
    ) %>%
      fct_relabel(\(x) str_replace(x, " ", "\n"))
  )


plot_data <- plot_samples %>%
  inner_join(
    yamanaka_ratios_rpk %>%
      filter(
        count_type == "rpk"
      ) %>%
      mutate(
        count_total = count_cds + count_utrs
      ),
    by = "sample_accession"
  )

baseline_data <- plot_data %>%
  filter(
    source_name == "5iLAF SSEA4- subpopulation UCLA1 hESCs"
  ) %>%
  group_by(gene_name, study_name) %>%
  summarize(
    ratio = 10^(sum(log10(ratio)) / n()),
    .groups = "drop"
  )

RATIO_ADDED <- min(na.omit(plot_data$ratio)) / 2

breaks <- 10^(-10:10)
minor_breaks <- sort(unique(c(rep(1:9, 11)*(10^rep(0:10, each=9)), (10^rep(-10:0, each=9)) / rep(1:9, 11))))

LOW_COUNT_THRESHOLD <- 30

p <- plot_data %>%
  mutate(
    ratio = if_else(!is.finite(ratio), RATIO_ADDED, ratio),
    counts_low = count_total < LOW_COUNT_THRESHOLD,
    count_total_bin = cut(count_total, breaks = c(-Inf, 50, Inf), labels = paste0(c("<", "≥"), LOW_COUNT_THRESHOLD), ordered_result = TRUE)
  ) %>%
  ggplot(
    aes(x = sample_group, y = ratio, shape = study_name, color = study_name)
  ) +
  geom_hline(yintercept = RATIO_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = ratio, color = study_name),
    data = baseline_data,
    show.legend = FALSE
  ) +
  geom_quasirandom(
    aes(alpha = count_total_bin)
  ) +
  scale_shape_manual(
    values = c(
      "Buckberry Nature 2023" = 16,
      "Ji CSC 2016" = 17,
      "Liu Nat Met 2017" = 3,
      "Pastor CSC 2016" = 23
    )
  ) +
  scale_alpha_manual(values = set_names(c(0.5, 1), paste0(c("<", "≥"), LOW_COUNT_THRESHOLD))) +
  paletteer::scale_color_paletteer_d("tidyquant::tq_light") +
  scale_y_log10(breaks = c(0.1, 1, 10, 100, 1000), minor_breaks = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = rel(.8)),
    legend.key.size = unit(8, "pt"),
    legend.text = element_text(size = unit(8, "pt")),
    legend.title = element_text(size = rel(.8))
    # legend.position = "top",
    # legend.direction = "vertical",
    # legend.box = "horizontal"
  ) +
  facet_wrap(~gene_name) +
  labs(
    y = "CDS / UTR Ratio", x = NULL, shape = "Source", color = "Source", alpha = "Total count"
  )

ggsave(
  here("plots", "yamanaka_ratios_select_samples_log_star_rpk.pdf"),
  p, width = 7.5, height = 3,
  dev = Cairo::CairoPDF
)
```


All but with buckberry as reference

```{r}
baseline_data <- plot_data %>%
  filter(
    treatment == "Control ESC",
    study_name == "Buckberry Nature 2023"
  ) %>%
  group_by(gene_name, study_name) %>%
  summarize(
    ratio = 10^(sum(log10(ratio)) / n()),
    .groups = "drop"
  )

RATIO_ADDED <- min(na.omit(plot_data$ratio)) / 2

breaks <- 10^(-10:10)
minor_breaks <- sort(unique(c(rep(1:9, 11)*(10^rep(0:10, each=9)), (10^rep(-10:0, each=9)) / rep(1:9, 11))))

p <- plot_data %>%
  mutate(
    ratio = if_else(!is.finite(ratio), RATIO_ADDED, ratio),
    counts_low = count_total < 50,
    count_total_bin = cut(count_total, breaks = c(-Inf, 50, Inf), labels = paste0(c("<", "≥"), LOW_COUNT_THRESHOLD), ordered_result = TRUE)
  ) %>%
  ggplot(
    aes(x = sample_group, y = ratio, shape = study_name, color = study_name)
  ) +
  geom_hline(yintercept = RATIO_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = ratio, color = study_name),
    data = baseline_data,
    show.legend = FALSE
  ) +
    geom_quasirandom(
    aes(alpha = count_total_bin)
  ) +
  scale_shape_manual(
    values = c(
      "Buckberry Nature 2023" = 16,
      "Ji CSC 2016" = 17,
      "Liu Nat Met 2017" = 3,
      "Pastor CSC 2016" = 23
    )
  ) +
  scale_alpha_manual(values = set_names(c(0.5, 1), paste0(c("<", "≥"), LOW_COUNT_THRESHOLD))) +
  paletteer::scale_color_paletteer_d("tidyquant::tq_light") +
  scale_y_log10(breaks = c(0.1, 1, 10, 100, 1000), minor_breaks = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = rel(.8)),
    legend.key.size = unit(8, "pt"),
    legend.text = element_text(size = unit(8, "pt")),
    legend.title = element_text(size = rel(.8))
    # legend.position = "top",
    # legend.direction = "vertical",
    # legend.box = "horizontal"
  ) +
  facet_wrap(~gene_name) +
  labs(
    y = "CDS / UTR Ratio", x = NULL, shape = "Source", color = "Source", alpha = "Total count"
  )


ggsave(
  here("plots", "yamanaka_ratios_select_samples_log_star_rpk_buckberry_reference.pdf"),
  p, width = 7.5, height = 3,
  dev = Cairo::CairoPDF
)

```


Without Pastor, use buckberry as reference

```{r}
baseline_data <- plot_data %>%
  filter(
    treatment == "Control ESC",
    study_name == "Buckberry Nature 2023"
  ) %>%
  group_by(gene_name, study_name) %>%
  summarize(
    ratio = 10^(sum(log10(ratio)) / n()),
    .groups = "drop"
  )

RATIO_ADDED <- min(na.omit(plot_data$ratio)) / 2

breaks <- 10^(-10:10)
minor_breaks <- sort(unique(c(rep(1:9, 11)*(10^rep(0:10, each=9)), (10^rep(-10:0, each=9)) / rep(1:9, 11))))

p <- plot_data %>%
  filter(study_name != "Pastor CSC 2016") %>%
  mutate(
    ratio = if_else(!is.finite(ratio), RATIO_ADDED, ratio),
    counts_low = count_total < 50,
    count_total_bin = cut(count_total, breaks = c(-Inf, 50, Inf), labels = paste0(c("<", "≥"), LOW_COUNT_THRESHOLD), ordered_result = TRUE)
  ) %>%
  ggplot(
    aes(x = sample_group, y = ratio, shape = study_name, color = study_name)
  ) +
  geom_hline(yintercept = RATIO_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = ratio, color = study_name),
    data = baseline_data,
    show.legend = FALSE
  ) +
    geom_quasirandom(
    aes(alpha = count_total_bin)
  ) +
  scale_shape_manual(
    values = c(
      "Buckberry Nature 2023" = 16,
      "Ji CSC 2016" = 17,
      "Liu Nat Met 2017" = 3
      # "Pastor CSC 2016" = 23
    )
  ) +
  scale_alpha_manual(values = set_names(c(0.5, 1), paste0(c("<", "≥"), LOW_COUNT_THRESHOLD))) +
  paletteer::scale_color_paletteer_d("tidyquant::tq_light") +
  scale_y_log10(breaks = c(0.1, 1, 10, 100, 1000), minor_breaks = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = rel(.8)),
    legend.key.size = unit(8, "pt"),
    legend.text = element_text(size = unit(8, "pt")),
    legend.title = element_text(size = rel(.8))
    # legend.position = "top",
    # legend.direction = "vertical",
    # legend.box = "horizontal"
  ) +
  facet_wrap(~gene_name) +
  labs(
    y = "CDS / UTR Ratio", x = NULL, shape = "Source", color = "Source", alpha = "Total count"
  )


ggsave(
  here("plots", "yamanaka_ratios_select_samples_log_star_rpk_no_pastor.pdf"),
  p, width = 7.5, height = 3,
  dev = Cairo::CairoPDF
)

```


Only buckberry

```{r}
baseline_data <- plot_data %>%
  filter(
    treatment == "Control ESC",
    study_name == "Buckberry Nature 2023"
  ) %>%
  group_by(gene_name, study_name) %>%
  summarize(
    ratio = 10^(sum(log10(ratio)) / n()),
    .groups = "drop"
  )

RATIO_ADDED <- min(na.omit(plot_data$ratio)) / 2

breaks <- 10^(-10:10)
minor_breaks <- sort(unique(c(rep(1:9, 11)*(10^rep(0:10, each=9)), (10^rep(-10:0, each=9)) / rep(1:9, 11))))

p <- plot_data %>%
  filter(study_name == "Buckberry Nature 2023") %>%
  mutate(
    ratio = if_else(!is.finite(ratio), RATIO_ADDED, ratio),
    counts_low = count_total < 50,
    count_total_bin = cut(count_total, breaks = c(-Inf, 50, Inf), labels = paste0(c("<", "≥"), LOW_COUNT_THRESHOLD), ordered_result = TRUE)
  ) %>%
  ggplot(
    aes(x = sample_group, y = ratio)
  ) +
  geom_hline(yintercept = RATIO_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = ratio),
    data = baseline_data,
    show.legend = FALSE
  ) +
    geom_quasirandom(
    aes(alpha = count_total_bin)
  ) +
  scale_alpha_manual(values = set_names(c(0.5, 1), paste0(c("<", "≥"), LOW_COUNT_THRESHOLD))) +
  scale_y_log10(breaks = c(0.1, 1, 10, 100, 1000), minor_breaks = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = rel(.8)),
    legend.key.size = unit(8, "pt"),
    legend.text = element_text(size = unit(8, "pt")),
    legend.title = element_text(size = rel(.8))
    # legend.position = "top",
    # legend.direction = "vertical",
    # legend.box = "horizontal"
  ) +
  facet_wrap(~gene_name) +
  labs(
    y = "CDS / UTR Ratio", x = NULL, alpha = "Total count"
  )

ggsave(
  here("plots", "yamanaka_ratios_select_samples_log_star_rpk_buckberry_only.pdf"),
  p, width = 7.5, height = 3,
  dev = Cairo::CairoPDF
)
```


```{r}

plot_data_normalized <- plot_samples %>%
  inner_join(
    yamanaka_ratios_rpk %>%
      filter(
        count_type == "rpk"
      ),
    by = "sample_accession"
  ) %>%
  inner_join(
    baseline_data %>%
      select(-study_name) %>%
      rename(ratio_baseline = ratio),
    by = c("gene_name")
  ) %>%
  mutate(
    ratio_normalized = ratio / ratio_baseline
  )

RATIO_ADDED <- min(na.omit(plot_data_normalized$ratio_normalized)) / 2
breaks <- 10^(-10:10)
minor_breaks <- rep(1:9, 21)*(10^rep(0:10, each=9))
minor_breaks <- sort(unique(c(rep(1:9, 11)*(10^rep(0:10, each=9)), (10^rep(-10:0, each=9)) / rep(1:9, 11))))

p <- plot_data_normalized %>%
  mutate(
    ratio_normalized = if_else(!is.finite(ratio_normalized), RATIO_ADDED, ratio_normalized)
  ) %>%
  ggplot(
    aes(x = sample_group, y = ratio_normalized, shape = study_name, color = study_name)
  ) +
  geom_hline(yintercept = RATIO_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = ratio_normalized, color = study_name),
    data = tibble(gene_name = unique(plot_data_normalized$gene_name), ratio_normalized = 1, study_name = "Ji CSC 2016"),
    guides = "none"
  ) +
  geom_quasirandom() +
  scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
  theme_linedraw() +
  facet_wrap(~gene_name) +
  labs(
    y = "CDS / UTR Ratio", x = NULL, shape = "Source", color = "Source"
  )

```

```{r}

plot_data <- plot_samples %>%
  inner_join(
    salmon_yamanaka_ratios,
    by = "sample_accession"
  )

baseline_data <- plot_data %>%
  filter(
    study_name == "Ji CSC 2016"
  ) %>%
  group_by(gene_name, study_name) %>%
  summarize(
    across(c(with_utr, no_utr), mean),
    .groups = "drop"
  )

COUNTS_ADDED <- min(na.omit(plot_data$no_utr)) / 2

p <- plot_data %>%
  # mutate(
  #   no_utr = if_else(!is.finite(no_utr), COUNTS_ADDED, no_utr)
  # ) %>%
  ggplot(
    aes(x = sample_group, y = no_utr, shape = study_name, color = study_name)
  ) +
  # geom_hline(yintercept = COUNTS_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = no_utr, color = study_name),
    data = baseline_data,
    guides = "none"
  ) +
  geom_quasirandom() +
  # geom_jitter() +
  # scale_y_log10() +
  theme_linedraw() +
  ggh4x::facet_wrap2(~gene_name, scales = "free_y") +
  labs(
    y = "Exogenous expression (no UTR)", x = NULL, shape = "Source", color = "Source"
  )

```

```{r}

plot_data <- plot_samples %>%
  inner_join(
    salmon_yamanaka_ratios %>%
      select(-ratio) %>%
      pivot_longer(
        c(with_utr, no_utr),
        names_to = "feature_name",
        values_to = "tpm"
      ),
    by = "sample_accession"
  )

baseline_data <- plot_data %>%
  filter(
    study_name == "Ji CSC 2016"
  ) %>%
  group_by(gene_name, study_name, feature_name) %>%
  summarize(
    across(c(tpm), mean),
    .groups = "drop"
  )

COUNTS_ADDED <- min(na.omit(plot_data$tpm)) / 2

p <- plot_data %>%
  # mutate(
  #   no_utr = if_else(!is.finite(no_utr), COUNTS_ADDED, no_utr)
  # ) %>%
  ggplot(
    aes(x = sample_group, y = tpm, shape = study_name, color = feature_name)
  ) +
  # geom_hline(yintercept = COUNTS_ADDED, linetype = "dashed") +
  geom_hline(
    aes(yintercept = tpm, color = feature_name),
    data = baseline_data,
    guides = "none"
  ) +
  geom_quasirandom(aes(group = feature_name), dodge.width = 0.5) +
  # geom_jitter() +
  # scale_y_log10() +
  theme_linedraw() +
  ggh4x::facet_wrap2(~gene_name, scales = "free_y") +
  labs(
    y = "Exogenous expression (no UTR)", x = NULL, shape = "Source", color = "Source"
  )


```

